spring:
  datasource:
    #    driver-class-name: org.postgresql.Driver # 数据库驱动类名
    #    url: jdbc:postgresql://localhost:5432/robot # 数据库连接 URL
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver # 数据库驱动类名
    url: jdbc:p6spy:postgresql://43.139.205.93:15432/robot # 数据库连接 URL
    username: postgres # 数据库用户名
    password: catairobot # 数据库密码
    hikari: # HikariCP 连接池配置
      pool-name: AI-Robot-HikariCP # 自定义连接池名称
      auto-commit: true # 是否自动提交事务
      connection-timeout: 30000 # 连接超时时间（毫秒）
      idle-timeout: 600000 # 空闲连接存活最大时间（毫秒）
      max-lifetime: 1800000 # 连接最大存活时间（毫秒）
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 20 # 最大连接池大小
      connection-test-query: SELECT 1 # 连接测试查询
      validation-timeout: 5000 # 验证连接的有效性
  ai:
    #    deepseek:
    #      api-key: sk-xxx # 填写 DeepSeek Api Key, 改成你自己的
    #      base-url: https://api.deepseek.com # DeepSeek 的请求 URL, 可不填，默认值为 api.deepseek.com
    #      chat:
    #        options:
    #          model: deepseek-chat # 使用哪个模型 deepseek-reasoner 推理
    #          temperature: 0.8 # 温度值
    #    ollama:
    #      base-url: http://localhost:11434 # Ollama 服务的访问地址, 11434 端口是 Ollama 默认的启动端口
    #      chat:
    #        options: # 模型参数
    #          model: qwen3:14b # 指定 Ollama 使用的大模型名称，根据你实际安装的来，我运行的是 14b
    #          temperature: 0.7 # 温度值
    #    zhipuai:
    #      base-url: https://open.bigmodel.cn/api/paas # 智谱 AI 的请求 URL, 可不填，默认值为 open.bigmodel.cn/api/paas
    #      api-key: xxx # 填写智谱 AI 的 API Key, 该成你自己的
    #      chat:
    #        options: # 模型参数
    #          model: glm-4-air # 模型名称，使用智谱 AI 哪个模型
    #          temperature: 0.7 # 温度值
    #    openai:
    #      base-url: https://api.zhizengzeng.com/v1 # OpenAI 服务的访问地址，这里使用的第三方代理商：智增增
    #      api-key: xxx  # 填写智增增的 API Key, 该成你自己的
    #      chat:
    #        options:
    #          model: gpt-4o # 模型名称
    #          temperature: 0.7 # 温度值
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # OpenAI 服务的访问地址，这里使用的是阿里云百炼
      api-key: sk-3ba280e44d184f83a1210d36108db6f8  # 填写阿里百炼 API Key, 改成你自己的
#      chat:
#        options:
#          model: qwen-turbo # 模型名称 qwen-omni-turbo
#          temperature: 0.7 # 温度值
#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:/mcp-servers-config.json # 指定 MCP 服务的配置文件路径
#        toolcallback:
#          enabled: true # 开启 MCP 客户端的工具回调（Tool Callback）功能
#    mcp:
#      client:
#        type: sync # 客户端使用同步通信模式
#        request-timeout: 20s # 设置单次请求超时时间
#        sse: # SSE (Server-Sent Events) 流式响应配置
#          connections: # 定义 SSE 连接端点
#            qq-mcp-server: # 自定义连接名称（可任意命名）
#              url: http://localhost:8000 # MCP 服务实际地址


okhttp: # OkHttp 客户端配置
  connect-timeout: 5000    # 建立连接的最大等待时间（毫秒）
  read-timeout: 30000      # 读取数据的最大等待时间（毫秒）
  write-timeout: 15000     # 写入数据的最大等待时间（毫秒）
  max-idle-connections: 200 # 连接池中保持的最大空闲连接数
  keep-alive-duration: 5   # 空闲连接在连接池中的存活时间（分钟）

searxng: # SearXNG 搜索引擎配置
  url: http://43.139.205.93:18888/search # SearXNG 服务的 API 端点地址
  count: 10 # 每次从搜索结果中，提取的最大数量
